"""Shared trading domain constants."""

from __future__ import annotations


ALERT_ONLY_MODE = "alert_only"
PAPER_MODE = "paper"
LIVE_MODE = "live"
TRADING_MODES = frozenset({ALERT_ONLY_MODE, PAPER_MODE, LIVE_MODE})
PROTECTED_TRADING_MODES = frozenset({PAPER_MODE, LIVE_MODE})

EXECUTION_SIDE_LONG = "long"
EXECUTION_SIDE_SHORT = "short"
EXECUTION_SIDES = frozenset({EXECUTION_SIDE_LONG, EXECUTION_SIDE_SHORT})

BROKER_ACTION_BUY = "BUY"
BROKER_ACTION_SELL = "SELL"
BROKER_ACTIONS = frozenset({BROKER_ACTION_BUY, BROKER_ACTION_SELL})

SIGNAL_DIRECTION_BUY = "BUY"
SIGNAL_DIRECTION_SELL = "SELL"
SIGNAL_DIRECTIONS = frozenset({SIGNAL_DIRECTION_BUY, SIGNAL_DIRECTION_SELL})

ORDER_STATUS_PENDING_SUBMIT = "PendingSubmit"
ORDER_STATUS_PRE_SUBMITTED = "PreSubmitted"
ORDER_STATUS_SUBMITTED = "Submitted"
ORDER_STATUS_PARTIALLY_FILLED = "PartiallyFilled"
ORDER_STATUS_FILLED = "Filled"
ORDER_STATUS_CANCELLED = "Cancelled"
ORDER_STATUS_INACTIVE = "Inactive"
ORDER_STATUS_REJECTED = "Rejected"
TRADE_STATUS_CLOSED = "Closed"

ACTIVE_ORDER_STATUSES = frozenset(
    {
        ORDER_STATUS_PENDING_SUBMIT,
        ORDER_STATUS_PRE_SUBMITTED,
        ORDER_STATUS_SUBMITTED,
        ORDER_STATUS_PARTIALLY_FILLED,
    }
)
TERMINAL_ORDER_STATUSES = frozenset(
    {
        ORDER_STATUS_FILLED,
        ORDER_STATUS_CANCELLED,
        ORDER_STATUS_INACTIVE,
        ORDER_STATUS_REJECTED,
    }
)
KNOWN_ORDER_STATUSES = ACTIVE_ORDER_STATUSES | TERMINAL_ORDER_STATUSES
TERMINAL_TRADE_STATUSES = TERMINAL_ORDER_STATUSES | frozenset({TRADE_STATUS_CLOSED})
