"""Default settings shared by loaders and direct-use helpers."""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path


DEFAULT_TELEGRAM_ENABLED = True
DEFAULT_TELEGRAM_MAX_RETRIES = 3
DEFAULT_TELEGRAM_RETRY_DELAY_SECONDS = 2.0
DEFAULT_TELEGRAM_TIMEOUT_SECONDS = 10.0
DEFAULT_TELEGRAM_REQUIRE_CRITICAL_DELIVERY = True

DEFAULT_LOG_FILE_PATH = Path("logs") / "bot.log"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FORMAT = "%(asctime)s %(levelname)s [%(name)s] %(message)s"
DEFAULT_LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

DEFAULT_RUNTIME_ACTIVE_TRADE_MONITOR_SECONDS = 10

DEFAULT_EXECUTION_ENTRY_ORDER_TYPE = "market"

DEFAULT_HEALTH_MARKET_DATA_MAX_AGE_SECONDS = 7200
DEFAULT_HEALTH_LAST_PROCESSED_CANDLE_MAX_AGE_SECONDS = 10800
DEFAULT_HEALTH_REPEATED_ERROR_LIMIT = 3

DEFAULT_SIZING_MIN_QUANTITY = Decimal("1")
DEFAULT_SIZING_QUANTITY_STEP = Decimal("1")
DEFAULT_SIZING_ALLOW_FRACTIONAL = False

DEFAULT_STRATEGY_USE_HEIKIN_ASHI = False
DEFAULT_STRATEGY_ATR_LENGTH = 14
DEFAULT_STRATEGY_SL_ATR_MULT = 1.0
DEFAULT_STRATEGY_TP_ATR_MULT = 2.0
